name: flutter_icp
description: Flutter library for Internet Computer Protocol (ICP) blockchain operations
version: 1.0.0+1
homepage: https://github.com/your-org/flutter_icp

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_nft: ^1.0.0+1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  convert: ^3.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter: