name: flutter_icp
description: Flutter library for Internet Computer Protocol (ICP) blockchain operations
version: 1.3.0
homepage: https://github.com/libsFlutter/flutter_icp
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_yuku:
    path: ../flutter_yuku
  flutter_nft:
    path: ../flutter_nft
  # Socket.IO for real-time updates (latest version)
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  test: ^1.26.2
  coverage: ^1.15.0

flutter: