name: flutter_icp
description: Flutter library for Internet Computer Protocol (ICP) blockchain operations
version: 1.3.1
homepage: https://github.com/libsFlutter/flutter_icp
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_yuku:
    path: ../flutter_yuku
  flutter_nft:
    path: ../flutter_nft
  
  # Core Flutter
  flutter_bloc: ^8.1.4
  provider: ^6.1.1
  
  # Network & API
  dio: ^5.4.0
  http: ^1.1.2
  web3dart: ^3.0.0
  web_socket_channel: ^3.0.1
  socket_io_client: ^3.1.2  # For real-time updates
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^3.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Cryptography
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  qr_flutter: ^4.1.0
  
  # Utils
  intl: ^0.20.0
  uuid: ^4.2.2
  equatable: ^2.0.5
  collection: ^1.18.0
  async: ^2.11.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  test: ^1.24.8
  coverage: ^1.6.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  flutter_flavorizr: ^2.2.1

# For generating JSON serialization code
flutter:
  generate: true
  uses-material-design: true
  
  # Assets for the package
  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/

# For running the build_runner
dependency_overrides:
  pointycastle: ^4.0.0
  analyzer: 6.3.0
  args: 2.5.0
  async: 2.11.0
  boolean_selector: 2.1.1
  characters: 1.3.0
  clock: 1.1.1
  collection: 1.18.0
  fake_async: 1.3.1
  matcher: 0.12.13+1
  material_color_utilities: 0.8.0
  meta: 1.9.1
  path: 1.8.3
  source_span: 1.9.1
  stack_trace: 1.11.0
  stream_channel: 2.1.1
  string_scanner: 1.2.0
  term_glyph: 1.2.1
  test_api: 0.6.0
  vector_math: 2.1.4