name: flutter_icp
description: Flutter library for Internet Computer Protocol (ICP) blockchain operations - provides ICP-specific providers for flutter_yuku
version: 2.0.1
homepage: https://github.com/libsFlutter/flutter_icp

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_yuku: ^2.0.3
  
  # Core Flutter
  flutter_bloc: ^8.1.4
  provider: ^6.1.1
  
  # Network & API
  dio: ^5.4.0
  http: ^1.1.2
  web3dart: ^3.0.0
  web_socket_channel: ^3.0.1
  socket_io_client: ^3.1.2 
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^3.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Cryptography
  crypto: ^3.0.3
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  qr_flutter: ^4.1.0
  
  # Utils
  intl: ^0.20.0
  uuid: ^4.2.2
  equatable: ^2.0.5
  collection: ^1.18.0
  async: ^2.11.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^3.2.3
  test: ^1.24.8
  coverage: ^1.6.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
  flutter_flavorizr: ^2.2.1

dependency_overrides:
  flutter_yuku:
    path: ../flutter_yuku

# For generating JSON serialization code
flutter:
  generate: true
  uses-material-design: true

# For running the build_runner
# dependency_overrides:
#   pointycastle: ^4.0.0