name: flutter_icp
description: Flutter library for Internet Computer Protocol (ICP) blockchain operations
version: 1.2.1+5
homepage: https://github.com/libsFlutter/flutter_icp

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_nft: ^1.0.0+1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  crypto: ^3.0.6
  convert: ^3.1.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  # Socket.IO for real-time updates (compatible version)
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.7.1
  json_serializable: ^6.8.0
  test: ^1.25.8
  coverage: ^1.10.0

flutter: